"""
finance_app.py — annotated reference implementation
====================================================

The backend for the finance_app architecture.
Serves the web UI (static/index.html: login form -> chat interface) and the
API endpoints behind it.

Entitlement model (matches Setup steps S2-S4 in infra.py and the agent's
TIER_TOOLS table in langgraph_bedrock.py):

    user    groups                               TIER scopes in JWT       agent tools
    --------------------------------------------------------------------------------
    Sarah   finance-agent-users + premium-users  basic.invoke +           weather, transactions,
                                                 premium.invoke           calculator, currency
    John    finance-agent-users                  basic.invoke             weather, transactions
                                                                          (own rows only)

    (scopes are per-TIER, not per-tool; premium.invoke is minted only when
    BOTH groups are present — premium alone grants nothing)

Sarah's journey through this file:

    PHASE 0  (runs once, at `uvicorn finance_app:app` startup)
        - fetch the Cognito client secret from Secrets Manager   [section 1]
        - fetch + cache the pool's public keys (JWKS)            [section 2]

    PHASE 1  (once per session)
        - GET  /      : the login page (then chat UI)            [section 8]
        - POST /login : Sarah's password -> Cognito -> JWTs      [section 4]
        - POST /refresh: hourly, silent token renewal            [section 5]

    PHASE 2  (every single message)
        - current_user(): LOCAL JWT verification, no Cognito     [section 6]
        - POST /chat: entitlement gate -> AgentCore Runtime      [section 7]

Three credentials live in this process, each with exactly one job:

    IAM keys (config app_profile)     -> sign the Secrets Manager call
    Cognito client secret             -> prove logins come from finance_app
    JWKS public keys                  -> verify JWTs users send back to us
"""

import base64
import hashlib
import hmac
import json
import os

import boto3
import jwt                      # pip install "pyjwt[crypto]"
from jwt import PyJWKClient
from fastapi import FastAPI, Depends, HTTPException, Request, Response
from fastapi.responses import FileResponse, JSONResponse
from fastapi.security import HTTPBearer, HTTPAuthorizationCredentials
from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Configuration — ONE file: infra_outputs.json, the handoff written into this
# directory by `python infra.py create` / `deploy-agent` (run from ../infra).
# The server never reads the admin project's config.yaml; everything it needs
# (ids + a server_config block) is stamped into the handoff. Nothing is
# hardcoded here; change names in ../infra/config.yaml and re-run create.
# ---------------------------------------------------------------------------
from pathlib import Path

_HERE = Path(__file__).parent
try:
    _out = json.loads((_HERE / "infra_outputs.json").read_text())
    _scfg = _out["server_config"]
except (FileNotFoundError, KeyError) as e:
    raise RuntimeError(
        "server/infra_outputs.json missing or predates the server_config "
        "handoff — run `python infra.py create` in ../infra to (re)generate it."
    ) from e

REGION = _scfg["region"]
POOL_ID = _out["pool_id"]                       # generated by infra.py (S1)
SECRET_NAME = _scfg["secret_name"]              # Secrets Manager entry (S6)
# Agent ARN: written to the handoff by `python infra.py deploy-agent`.
AGENT_ARN = _out.get("agent_arn") or ""
if not AGENT_ARN:
    raise RuntimeError(
        "No agent deployed: run `python infra.py deploy-agent` in ../infra first."
    )
# The agent admission group is EXPLICIT in config — never derived from the
# order of the groups mapping (reordering YAML must not change security).
AGENT_GROUP = _scfg["agent_admission_group"]
if AGENT_GROUP not in _scfg["groups"]:
    raise RuntimeError(
        f"handoff: agent_admission_group '{AGENT_GROUP}' is not one of the "
        f"provisioned groups: {_scfg['groups']}"
    )

# The agent's MODE (gateway vs local), its model, and the gateway MCP URLs
# are baked into the agent container's ENVIRONMENT at deploy time (infra.py
# deploy_agent), NOT sent from here. This app forwards only the prompt and the
# user's token — see /chat. Keeping runtime config out of the request payload
# is what stops a direct Runtime caller from flipping mode or the model.

# The pool's base URL. It appears in two roles:
#   - as the `iss` (issuer) claim stamped inside every token Cognito mints
#   - as the root of the JWKS URL we download the public keys from
# Verifying `iss` == this exact string is what rejects valid-looking tokens
# minted by SOMEONE ELSE'S pool.
ISSUER = f"https://cognito-idp.{REGION}.amazonaws.com/{POOL_ID}"


# ===========================================================================
# PHASE 0, section 1 — fetch the client secret (the app's own ID card)
# ===========================================================================
# This is the ONLY place IAM credentials are used by the app process.
# The request below is SigV4-signed with the keys of the `app_profile` named
# in the handoff (sandbox: same as admin_profile; production: least-privilege
# invoker user). The IAM identity must be allowed to read this secret.
#
# Why at startup and not lazily inside /login?
#   - one vault read for the process lifetime instead of one per login
#   - fail-fast: if IAM keys or the secret are misconfigured, the app
#     refuses to boot with a clear error, instead of failing at the
#     first real user's login.
#
# After these lines the secret exists in three places in the universe:
# Cognito's config, Secrets Manager, and this process's RAM. Never on disk.
session = boto3.Session(profile_name=_scfg["app_profile"])
_secrets_client = session.client("secretsmanager", region_name=REGION)
_secret = json.loads(
    _secrets_client.get_secret_value(SecretId=SECRET_NAME)["SecretString"]
)
CLIENT_ID: str = _secret["client_id"]          # public-ish identifier
CLIENT_SECRET: str = _secret["client_secret"]  # the actual secret


# ===========================================================================
# PHASE 0, section 2 — fetch + cache the JWKS (the forgery-detector lamp)
# ===========================================================================
# PyJWKClient downloads {ISSUER}/.well-known/jwks.json ONCE and caches the
# pool's RSA *public* keys in memory. Plain HTTPS, no auth — these keys are
# public by design: they can only VERIFY signatures, never create them.
# (The matching private key never leaves Cognito.)
#
# Clock discipline (this answers "how often does this change?"):
#   - JWTs   : expire every 60 minutes — minted constantly, per user
#   - JWKS   : per-POOL, stable for years; every token of every user is
#              signed by the same pool key
# Token expiry does NOT mean key expiry: a refreshed token is new *content*
# signed by the same old key, so this startup cache verifies tokens
# indefinitely.
#
# Rare rotation is handled with zero code on our side: if a token arrives
# whose header `kid` (key id) is not in the cache, PyJWKClient re-fetches
# the JWKS once, finds the new key, and carries on.
jwks = PyJWKClient(f"{ISSUER}/.well-known/jwks.json")


# ===========================================================================
# Section 3 — AWS/Cognito clients
# ===========================================================================
# Note the asymmetry, it is deliberate:
#   - `cognito` is a PLAIN client (no profile). InitiateAuth is an
#     unauthenticated API: the proof it carries is IN THE BODY
#     (password + SECRET_HASH), not in an AWS signature.
#   - the Runtime call in /chat (Phase 2, JWT-inbound design) uses Sarah's
#     own bearer token, so no AWS client is needed for invocation either.
cognito = boto3.client("cognito-idp", region_name=REGION)

bearer = HTTPBearer()      # FastAPI helper: extracts "Authorization: Bearer x"
app = FastAPI(title="finance_app")


# ===========================================================================
# HTTPS enforcement — the /login password and every bearer token cross the
# wire on the browser->app hop, so that hop MUST be TLS. (The app->Cognito hop
# is always HTTPS: boto3 has no plaintext option.) Two layers, defence in depth:
#
#   1. DEPLOYMENT is the real guarantee: terminate TLS in front of uvicorn
#      (ALB / CloudFront / nginx with an ACM or Let's Encrypt cert), run
#      uvicorn with `--proxy-headers --forwarded-allow-ips=<proxy CIDR>` so it
#      reads the proxy's X-Forwarded-Proto and won't trust that header from
#      arbitrary clients, and never expose uvicorn's plain-HTTP port to the
#      internet. For local TLS instead, use uvicorn's --ssl-keyfile/--ssl-certfile.
#
#   2. This GUARD is a safety net so a plaintext misdeploy fails LOUDLY, not
#      silently: it refuses any request whose ORIGINAL (browser) scheme wasn't
#      https, and stamps HSTS so browsers refuse plain HTTP for this origin
#      thereafter. localhost is exempt so dev works without certs; set
#      REQUIRE_HTTPS=false to disable the guard entirely for local plaintext.
# ===========================================================================
REQUIRE_HTTPS = os.environ.get("REQUIRE_HTTPS", "true").lower() != "false"
_LOCAL_HOSTS = {"localhost", "127.0.0.1", "::1"}


def _origin_scheme(request: Request) -> str:
    """The scheme the BROWSER used. Behind a TLS-terminating proxy the app
    itself sees plain http on the internal hop; the proxy records the real
    client scheme in X-Forwarded-Proto (trustworthy only because uvicorn's
    --forwarded-allow-ips restricts who may set it)."""
    xfp = request.headers.get("x-forwarded-proto")
    if xfp:
        return xfp.split(",")[0].strip().lower()   # may be "https, http" via chained proxies
    return request.url.scheme


@app.middleware("http")
async def require_https(request: Request, call_next):
    if REQUIRE_HTTPS and _origin_scheme(request) != "https":
        # localhost is exempt so local dev works over http without certs.
        if (request.url.hostname or "").lower() not in _LOCAL_HOSTS:
            return JSONResponse(status_code=403, content={"detail": "HTTPS required"})
    response = await call_next(request)
    # Pin the browser to HTTPS for this origin going forward (ignored over http).
    response.headers.setdefault(
        "Strict-Transport-Security", "max-age=31536000; includeSubDomains"
    )
    return response


def secret_hash(username: str) -> str:
    """The app's signature on a login attempt.

    SECRET_HASH = Base64( HMAC-SHA256( key=CLIENT_SECRET,
                                       msg=username + CLIENT_ID ) )

    Cognito recomputes this with its own copy of the secret; a mismatch
    (or absence) -> NotAuthorizedException before the password is even
    looked at. This is what makes a leaked CLIENT_ID useless on its own,
    and why Sarah's password only works WHEN SUBMITTED THROUGH THIS APP.

    Gotcha encoded here: for USER_PASSWORD_AUTH the `username` is what the
    user typed (email); for REFRESH_TOKEN_AUTH it must be the user's `sub`.
    """
    digest = hmac.new(
        CLIENT_SECRET.encode(),
        (username + CLIENT_ID).encode(),
        hashlib.sha256,
    ).digest()
    return base64.b64encode(digest).decode()


# ---------------------------------------------------------------------------
# Refresh-token cookies — the 30-day credential stays OUT of JavaScript.
#
# The refresh token (and the `sub` needed to compute its SECRET_HASH) live in
# httpOnly cookies the browser will not expose to page scripts. So an XSS can
# steal at most the 60-minute access token in JS memory, never the 30-day
# refresh token — the blast radius of a script injection shrinks from a month
# to the rest of one hour. Attributes:
#   httponly  -> unreadable/unwritable by JS (the whole point)
#   secure    -> only sent over HTTPS (skipped for a plaintext dev origin, or
#                the cookie would never be sent back on http://localhost)
#   samesite=strict -> never attached to cross-site requests => no CSRF surface
#   path=/refresh   -> the browser only sends it to /refresh (and /logout
#                clears it), not to /chat or the page load
#   (no max-age) -> a SESSION cookie: cleared when the browser closes, keeping
#                close to the old "closing the tab signs you out" behaviour.
# ---------------------------------------------------------------------------
def _set_refresh_cookies(request: Request, response: Response,
                         refresh_token: str, sub: str) -> None:
    secure = _origin_scheme(request) == "https"
    opts = dict(httponly=True, secure=secure, samesite="strict", path="/refresh")
    response.set_cookie("refresh_token", refresh_token, **opts)
    response.set_cookie("rt_sub", sub, **opts)   # sub isn't secret, but keep JS clean


def _clear_refresh_cookies(response: Response) -> None:
    response.delete_cookie("refresh_token", path="/refresh")
    response.delete_cookie("rt_sub", path="/refresh")


# ===========================================================================
# PHASE 1, section 4 — /login : password in, entitlement-rich JWTs out
# ===========================================================================
# The PROXY login style: the user types into OUR textboxes (served by
# section 8), the browser POSTs here, and WE call Cognito server-to-server.
# No redirects; the browser never sees a Cognito URL.
#
# Two identities are presented to Cognito in ONE request body:
#   USERNAME + PASSWORD     -> identifies and proves THE USER
#   ClientId + SECRET_HASH  -> identifies and proves FINANCE_APP
#
# Cognito then: validates client -> validates SECRET_HASH -> validates the
# password -> runs the pre-token-generation Lambda, which turns groups into
# tool scopes INSIDE the signed token:
#   Sarah (both groups)          -> scope: weather.read + calculator.use
#   John  (finance-agent-users)  -> scope: weather.read only
class LoginRequest(BaseModel):
    username: str
    password: str


@app.post("/login")
def login(body: LoginRequest, request: Request, response: Response):
    try:
        resp = cognito.initiate_auth(
            ClientId=CLIENT_ID,
            AuthFlow="USER_PASSWORD_AUTH",
            AuthParameters={
                "USERNAME": body.username,
                "PASSWORD": body.password,                    # transits RAM only;
                "SECRET_HASH": secret_hash(body.username),    # never logged, never stored
            },
        )
    except (cognito.exceptions.NotAuthorizedException,
            cognito.exceptions.UserNotFoundException):
        # Same message for both cases on purpose: don't leak which
        # usernames exist.
        raise HTTPException(401, "Wrong username or password")

    tokens = resp["AuthenticationResult"]

    # Decode the access token (no signature check needed — Cognito just handed
    # it to us over TLS). We read two things from it:
    #   - cognito:groups, to reject ineligible users AT LOGIN (below) so a pool
    #     member in no groups fails fast here instead of after their first
    #     /chat. This is a UX early-exit, NOT the security boundary: /chat and
    #     the agent still gate EVERY request on the cryptographically VERIFIED
    #     token, because a token can outlive a group change (or arrive via
    #     /refresh). Never rely on this check alone.
    #   - sub, the user's permanent id, which the browser needs for /refresh.
    claims = jwt.decode(tokens["AccessToken"], options={"verify_signature": False})
    if AGENT_GROUP not in claims.get("cognito:groups", []):
        # Authenticated (correct password) but not authorized -> 403, not 401.
        raise HTTPException(403, "Your account is not eligible for this application")
    sub = claims["sub"]

    # Park the 30-day refresh token + sub in httpOnly cookies (see
    # _set_refresh_cookies) — the browser will replay them to /refresh on its
    # own, and page JS can never read them.
    _set_refresh_cookies(request, response, tokens["RefreshToken"], sub)

    # Only the short-lived access token goes back in the body, for JS memory.
    # Claims: sub, client_id, iss, exp, token_use, cognito:groups, scope.
    return {
        "access_token": tokens["AccessToken"],
        "expires_in": tokens["ExpiresIn"],
    }


# ===========================================================================
# PHASE 1, section 5 — /refresh : the hourly silent renewal
# ===========================================================================
# At t=60min the access token's `exp` passes; current_user() starts
# returning 401. The browser then calls this endpoint; the user types
# nothing and notices nothing. This is also the moment entitlement changes
# take effect (new groups -> new scopes in the fresh token) and the moment
# a disabled user is truly locked out.
@app.post("/refresh")
def refresh(request: Request, response: Response):
    # The refresh token and sub come from the httpOnly cookies the browser
    # attached automatically — NOT from the request body. Page JS never had
    # them to send.
    refresh_token = request.cookies.get("refresh_token")
    sub = request.cookies.get("rt_sub")
    if not refresh_token or not sub:
        raise HTTPException(401, "No refresh session — please sign in again")

    try:
        resp = cognito.initiate_auth(
            ClientId=CLIENT_ID,
            AuthFlow="REFRESH_TOKEN_AUTH",
            AuthParameters={
                "REFRESH_TOKEN": refresh_token,
                "SECRET_HASH": secret_hash(sub),   # sub, NOT email — see secret_hash()
            },
        )
    except cognito.exceptions.NotAuthorizedException:
        _clear_refresh_cookies(response)   # dead credential — drop the stale cookies
        raise HTTPException(401, "Refresh token expired or revoked")

    access_token = resp["AuthenticationResult"]["AccessToken"]
    # Same eligibility gate as /login: a user removed from the group is turned
    # away at the hourly refresh, rather than lingering with a working token
    # until /chat rejects them. UX early-exit only — /chat and the agent still
    # gate every request on the cryptographically verified token.
    claims = jwt.decode(access_token, options={"verify_signature": False})
    if AGENT_GROUP not in claims.get("cognito:groups", []):
        _clear_refresh_cookies(response)
        raise HTTPException(403, "Your account is not eligible for this application")
    return {"access_token": access_token}


# ===========================================================================
# PHASE 1, section 5b — /logout : drop the refresh cookies
# ===========================================================================
# The access token is only in JS memory (gone when the page clears it), but
# the refresh cookie would otherwise linger for the browser session. /logout
# expires it server-side so "sign out" is real, not just a UI reset.
@app.post("/logout")
def logout(response: Response):
    _clear_refresh_cookies(response)
    return {"ok": True}


# ===========================================================================
# PHASE 2, section 6 — current_user : LOCAL verification on every request
# ===========================================================================
# THE two lines this whole design pivots on are marked below. They run as a
# FastAPI dependency before /chat's body executes.
#
# "Local" means: pure CPU math inside this process. Sequence over time:
#
#     STARTUP    jwks downloaded            <- one HTTPS GET, cached
#     /chat #1   hash + RSA check           <- microseconds, zero network
#     /chat #2   hash + RSA check
#     /chat #N   hash + RSA check           <- still zero Cognito traffic
#
# Cognito is only contacted when something must be MINTED (login/refresh);
# verification never goes there. Known trade-off: disabling a user mid-hour
# leaves their current token valid until `exp` (<= 60 min residual) —
# shorten token validity if faster revocation matters.
def current_user(
    cred: HTTPAuthorizationCredentials = Depends(bearer),
) -> dict:
    token = cred.credentials
    try:
        # (1) Read the token header's `kid`, pick the matching cached
        #     public key. Cache miss (rare rotation) -> one silent refetch.
        key = jwks.get_signing_key_from_jwt(token)

        # (2) The verification itself. Internally:
        #       - SHA-256 over the token's header.payload bytes
        #       - RSA public-key operation on the signature, recovering the
        #         hash Cognito computed at mint time
        #       - equal? -> genuinely minted by the pool's private key AND
        #         not altered by a single character since
        #       - also enforces exp (not expired) and iss (OUR pool)
        #     Change one char of the payload (e.g. add a scope) and this
        #     raises InvalidSignatureError -> 401.
        claims = jwt.decode(token, key.key, algorithms=["RS256"], issuer=ISSUER)
    except jwt.PyJWTError as e:
        raise HTTPException(401, f"Invalid token: {e}")

    # Signature checks WHO minted it; these check it's the right KIND:
    # minted through OUR app client (a valid token from another app client
    # on the same pool fails here), and an access token, not an ID token.
    if claims.get("client_id") != CLIENT_ID or claims.get("token_use") != "access":
        raise HTTPException(401, "Token not issued for this app client")

    return claims   # trusted from here on: sub, cognito:groups, scope, ...


# ===========================================================================
# PHASE 2, section 7 — /chat : entitlement gate, then invoke the agent
# ===========================================================================
# JWT-inbound design (target architecture, milestone M4): we forward the
# USER'S OWN token to the Runtime, whose customJWTAuthorizer re-validates
# it against the same pool — independently of us. Our IAM keys play no part
# in invocation. (Pre-M4 IAM design: boto3 invoke_agent_runtime instead.)
#
# Note the division of labour for tools:
#   - HERE we only gate "may this user use the agent AT ALL?" (group check).
#     Sarah AND John both pass — both are in finance-agent-users.
#   - WHICH tools each gets (Sarah: weather + calculator, John: weather
#     only) is decided downstream from the token's `scope` claim — by the
#     agent's TIER_TOOLS filter today, by the gateway allowedScopes tiers after M3/M5.
#     This app never hardcodes per-tool rules; it just forwards the token.
import urllib.parse
import requests

RUNTIME_URL = (
    f"https://bedrock-agentcore.{REGION}.amazonaws.com/runtimes/"
    + urllib.parse.quote(AGENT_ARN, safe="")
    + "/invocations?qualifier=DEFAULT"
)


# Prompt length cap — a full page or so. Front-door validation for normal
# traffic; the agent re-checks the SAME limit (langgraph_bedrock.py's
# MAX_PROMPT_CHARS) since it's directly reachable, and the UI reflects it via
# the input's maxlength. Keep all three in sync.
MAX_PROMPT_CHARS = 4000


class ChatRequest(BaseModel):
    prompt: str = Field(min_length=1, max_length=MAX_PROMPT_CHARS)


@app.post("/chat")
def chat(
    body: ChatRequest,
    cred: HTTPAuthorizationCredentials = Depends(bearer),
):
    # Verify first (section 6's checks), THEN use the claims.
    user = current_user(cred)

    # Entitlement gate — authorization, distinct from authentication.
    # A pool user in NO groups is authenticated but stops HERE with 403
    # and never touches AWS. The group claim is inside the signed token:
    # it cannot be added without breaking the signature check above.
    # (AGENT_GROUP is set explicitly in the infra config, via the handoff.)
    if AGENT_GROUP not in user.get("cognito:groups", []):
        raise HTTPException(403, "Not authorized to use the finance agent")

    # Session id from the VERIFIED sub — never from anything the client
    # sends. This is the per-user microVM isolation guarantee: John's token
    # carries John's sub, so he lands in his own VM, always.
    # (sub is a 36-char UUID, satisfying the >=33 char session-id minimum.)
    # Defence in depth: the agent re-derives finance-<sub> from the payload
    # token it verifies and REJECTS any session id that doesn't match — so a
    # caller reaching the Runtime directly can't forge another user's session
    # (the Runtime itself doesn't bind the session header to the token).
    session_id = f"finance-{user['sub']}"

    try:
        resp = requests.post(
            RUNTIME_URL,
            headers={
                # The user's token, re-validated BY THE RUNTIME itself
                "Authorization": f"Bearer {cred.credentials}",
                "X-Amzn-Bedrock-AgentCore-Runtime-Session-Id": session_id,
                "Content-Type": "application/json",
            },
            # Token also inside the payload: the agent VERIFIES it (langgraph_
            # bedrock.py's _verify_token) and reads its `scope` claim to bind only
            # the entitled tools, and in gateway mode presents it to the AgentCore
            # Gateways the same way. MODE, model, and gateway URLs are baked into
            # the agent's own environment at deploy time — deliberately NOT sent
            # from here, so a direct Runtime caller cannot override them.
            json={"prompt": body.prompt,
                  "access_token": cred.credentials},
            timeout=120,
        )
    except requests.RequestException as e:
        # Network-level failure (DNS/connect/timeout) — never reached the Runtime.
        raise HTTPException(502, f"Agent runtime unreachable: {e}")

    # Non-2xx from the Runtime (its JWT authorizer rejecting, a 5xx, etc.):
    # surface the status + body instead of the opaque 500 raise_for_status gives.
    if not resp.ok:
        raise HTTPException(502, f"Agent runtime error {resp.status_code}: {resp.text[:500]}")

    # The entrypoint returns a plain STRING; the Runtime hands it back JSON-
    # encoded, so resp.json() yields that string (the UI renders string-or-object).
    # Fall back to raw text if the body somehow isn't JSON — defensive: a
    # non-streaming string return is always JSON, but this avoids a 500 if not.
    try:
        reply = resp.json()
    except ValueError:
        reply = resp.text
    return {"reply": reply}


# ===========================================================================
# PHASE 1, section 8 — the web UI: login page, then the chat interface
# ===========================================================================
# One static page (static/index.html) drives the whole user experience:
#   1. shows username + password textboxes
#   2. POSTs them to /login (section 4); stores the returned tokens in JS
#   3. swaps to the chat interface; every message POSTs to /chat (section 7)
#      with "Authorization: Bearer <access_token>"
#   4. on a 401 (hourly expiry) silently calls /refresh and retries
# No Cognito URL, no redirect, no AWS anything ever reaches the browser.
@app.get("/")
def index():
    return FileResponse(_HERE / "static" / "index.html")


# ---------------------------------------------------------------------------
# Run (local, HTTP):   uvicorn finance_app:app --host 0.0.0.0 --port 8000
# Run (local, HTTPS):  make a throwaway self-signed cert once —
#     openssl req -x509 -newkey rsa:2048 -nodes -days 365 \
#         -keyout key.pem -out cert.pem -subj "/CN=localhost"
#   then serve TLS directly (browser warns on the self-signed cert; proceed):
#     uvicorn finance_app:app --host 0.0.0.0 --port 8443 \
#         --ssl-keyfile key.pem --ssl-certfile cert.pem
# Run (behind a TLS proxy): add --proxy-headers --forwarded-allow-ips=<proxy CIDR>
#
# HTTPS is non-negotiable in front of this: passwords transit /login and
# bearer tokens transit every other endpoint. The require_https middleware
# above enforces it (localhost exempt; REQUIRE_HTTPS=false to disable for
# plaintext dev) — but the real guarantee is TLS (self-signed cert locally, a
# proxy-terminated real cert in production).
# ---------------------------------------------------------------------------
