"""
tools_core.py — the shared bodies for the three demo tools
==========================================================

ONE implementation of each tool's logic, imported by BOTH execution
environments so the behaviour can never drift between them:

  * local mode   — langgraph_bedrock.py wraps each function in a LangChain
    @tool (its own name + docstring become the schema the model sees)
  * gateway mode — gateway_tools_lambda.py wraps each function in a
    tool_*(event) adapter that the AgentCore Gateway invokes

The two environments cannot import each other (the agent container has
LangChain/pydantic; the Lambda is stdlib-only), so the logic used to be
copy-pasted — which is how the local tool drifted to `weather` while the
gateway tool was `get_weather`. Centralising it here removes that class of
bug: there is exactly one body per tool.

Because the Lambda has NO third-party dependencies, this module MUST stay
**stdlib-only** (no langchain, no pydantic, no boto3 — identity resolution
for get_transactions happens in the CALLERS, never here). infra.py ships this
file inside the Lambda deployment zip alongside the handler; the agent
container gets it for free (the whole directory is copied into the image at
build time).

`where` only annotates the provenance tag — "" when the body runs locally,
" @lambda" when it runs in the gateway Lambda. The result is otherwise
identical, which is exactly the property this module guarantees.
"""

import csv
import datetime
import math
import operator
import pathlib

# get_transactions: newest-first cap when no date range is given
MAX_TRANSACTIONS = 10


def _tag(name: str, where: str) -> str:
    return f"[TOOL: {name}{where}]"


def get_weather(country: str, where: str = "") -> str:
    """Return the (dummy) current weather for a country."""
    country = (country or "").strip() or "an unspecified location"
    # Deterministic sunny/cloudy pick (no randomness — the result must be
    # stable across the agent container and the Lambda for the same input):
    # first letter a-j -> sunny, k onwards -> cloudy.
    condition = "sunny" if country.lower()[0] < "k" else "cloudy"
    return f"{_tag('get_weather', where)} The weather in {country} is {condition}"


def calculator(expression: str, where: str = "") -> str:
    """Safely evaluate a mathematical expression string."""
    tag = _tag("calculator", where)
    try:
        # Whitelisted names only; no builtins — eval can reach nothing else.
        safe_dict = {
            "__builtins__": {},
            "abs": abs, "round": round, "min": min, "max": max,
            "sum": sum, "pow": pow,
            # Math functions
            "sqrt": math.sqrt, "sin": math.sin, "cos": math.cos, "tan": math.tan,
            "log": math.log, "log10": math.log10, "exp": math.exp,
            "pi": math.pi, "e": math.e,
            "ceil": math.ceil, "floor": math.floor,
            "degrees": math.degrees, "radians": math.radians,
            # Basic operators (for explicit use)
            "add": operator.add, "sub": operator.sub,
            "mul": operator.mul, "truediv": operator.truediv,
        }
        return f"{tag} {eval(expression, safe_dict)}"
    except ZeroDivisionError:
        return f"{tag} Error: Division by zero"
    except ValueError as e:
        return f"{tag} Error: Invalid value - {e}"
    except SyntaxError:
        return f"{tag} Error: Invalid mathematical expression"
    except Exception as e:  # noqa: BLE001 — tool results must never raise
        return f"{tag} Error: {e}"


def get_transactions(user_id: str, start_date: str = "", end_date: str = "",
                     where: str = "", csv_path: str = "") -> str:
    """Return the caller's transactions from the bundled synthetic CSV.

    user_id is the caller's VERIFIED Cognito sub — resolved by the execution
    environment (the gateway Lambda via cognito get_user on an injected
    access token; local mode from the agent's signature-verified claims) and
    NEVER by the model. Row-level isolation therefore holds even against
    prompt injection: the model has no identity parameter to manipulate.

    start_date/end_date (ISO YYYY-MM-DD, both optional) filter an inclusive
    range; with no range the newest MAX_TRANSACTIONS rows are returned.
    csv_path is a test seam — production callers use the default: the
    transactions.csv generated by infra.py's S9 step, shipped next to this
    file in both the Lambda zip and the agent container.
    """
    tag = _tag("get_transactions", where)
    path = pathlib.Path(csv_path) if csv_path else \
        pathlib.Path(__file__).parent / "transactions.csv"
    if not path.exists():
        return (f"{tag} Transaction data is not available "
                "(admin: run `python infra.py create` to generate it).")
    try:
        start = datetime.date.fromisoformat(start_date) if start_date else None
        end = datetime.date.fromisoformat(end_date) if end_date else None
    except ValueError:
        return f"{tag} Error: dates must be in YYYY-MM-DD format"

    rows = []
    with path.open(newline="") as f:
        for row in csv.DictReader(f):
            if row["user_id"] != user_id:
                continue
            d = datetime.date.fromisoformat(row["date"])
            if (start and d < start) or (end and d > end):
                continue
            rows.append((d, row))
    rows.sort(key=lambda r: r[0], reverse=True)
    if not (start or end):
        rows = rows[:MAX_TRANSACTIONS]

    if not rows:
        period = (f" between {start_date or 'the beginning'} and "
                  f"{end_date or 'today'}") if (start or end) else ""
        return f"{tag} No transactions found{period}."
    lines = [
        f"{d.isoformat()}  {r['description']}  "
        f"{float(r['amount']):+.2f} {r['currency']}  ({r['category']})"
        for d, r in rows
    ]
    return f"{tag} {len(lines)} transaction(s), newest first:\n" + "\n".join(lines)
